Repository Igalia/WPEBackend-fdo, pull requests merged in 2019-09, with the labels that each got.

#73 wl_resource management fixes
  src/exported-image-egl.cpp
  src/view-backend-exportable-fdo-egl-private.h
  src/view-backend-exportable-fdo-egl.cpp
  src/view-backend-exportable-fdo.cpp
  src/view-backend-exportable-private.cpp
  src/view-backend-exportable-private.h
Labels: merge:wpebackend-fdo-1.2, merge:wpebackend-fdo-1.4

#77 CMake: Avoid target_link_libraries() with imported targets
  cmake/FindEGL.cmake
  cmake/FindWPE.cmake
Labels: merge:wpebackend-fdo-1.4

#78 cmake: Use imported targets for Wayland libraries
  CMakeLists.txt
  cmake/FindWayland.cmake
  cmake/FindWaylandEGL.cmake
Labels: enhancement

#79 Simplify Wayland version check
  CMakeLists.txt
  src/ws.cpp
Labels: enhancement

#81 Add functions to obtain the library version at runtime
  CMakeLists.txt
  include/wpe-fdo/version.h.cmake
  src/version.c
Labels: enhancement

#82 Use GLib functions for logging
  CMakeLists.txt
  src/ipc.cpp
  src/ws-client.cpp
  src/ws.cpp
Labels: enhancement
